### ISSUE TITLE
Bootstrap v4 Support

### ISSUE THREAD

**Issue by JumboLove** [maciej-gurban/responsive-bootstrap-toolkit#42]
Bootstrap v4 is going in a different direction for visibility classes:
http://v4-alpha.getbootstrap.com/layout/responsive-utilities/

The toolkit in its current state will not work with Bootstrap out of the box.

A quick change can be made to Bootstrap's Sass files to get most of the functionality back.

utilities/_visibility.scss

``` scss
// Responsive visibility utilities

@each $bp in map-keys($grid-breakpoints) {
  .hidden-#{$bp}-up {
    @include media-breakpoint-up($bp) {
      display: none !important;
    }
  }
  .hidden-#{$bp}-down {
    @include media-breakpoint-down($bp) {
      display: none !important;
    }
  }
  //add visible classes
  .visible-#{$bp} {
    display: none;

    @include media-breakpoint-only($bp) {
      display: block !important;
    }
  }
}
```

This is a quick solution that you can throw into the README if/until v4 is supported.

Thanks for the tool!
